### ISSUE TITLE
Allow abstract classes in protocol

### ISSUE THREAD

**Issue by fredrikbromee** [cinnober/msgcodec#3]
Currently all classes specified in a protocol need to be concrete, due to a check in com.cinnober.msgcodec.ProtocolDictionaryBuilder.GroupMeta.GroupMeta(Class<?>)

It would be nice if msgcodec would allow an abstract class in the protocol if it is also annotated with @Dynamic. Or maybe it would automatically become @Dynamic if it is abstract.

**Comment by mbrannstrom** [comment]
Message classes may now be abstract, regardless if dynamic or not. The Dynamic annotation still need to be explicit. 

Decoding abstract message classes will result in a DecodeException to be thrown. 

Note that due to a schema upgrade a sub class may be flattened to its super group class, and if that is abstract a DecodeException is thrown. 

For example the message classes `Request` and `Response` in [ProtocolUpgradeExample.java](../tree/5bd413120bb7abc88743fb025021de08d800a373/msgcodec-examples/src/main/java/com/cinnober/msgcodec/examples/upgrade/ProtocolUpgradeExample.java) could have been abstract, but the client would fail decoding `GetUserRsp` as `Response` in that case.
